[project]
name = "tools"
version = "0.1.0"
description = "Remote tools for Raspberry Pi."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "paramiko>=3.5.1",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
]
