[project]
name = "rpi-sound-machine"
version = "0.1.0"
description = "RPI application for playing sounds."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-mock>=3.14.1",
]
