[project]
name = "rpi-sound-machine"
version = "0.1.0"
description = "RPI application for playing sounds."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "pygame>=2.6.1",
]
