RPI_REMOTE_TOOLS_PATH := "rpi_remote_tools"
RPI_REMOTE_TOOLS_MODULE := "tools"

_rpi *args:
    @uv run --quiet --project {{RPI_REMOTE_TOOLS_PATH}} \
        python -m {{RPI_REMOTE_TOOLS_PATH}}.{{RPI_REMOTE_TOOLS_MODULE}} {{args}}

check configurations="{}":
    @# @echo "Using config: {{configurations}}"
    @# @just _rpi --rpi-check-app --configurations '{{configurations}}'
    @uv run --quiet --project {{RPI_REMOTE_TOOLS_PATH}} \
        python -m {{RPI_REMOTE_TOOLS_PATH}}.{{RPI_REMOTE_TOOLS_MODULE}} --rpi-check-app \
        --configurations '{{configurations}}'

# Killing running application on Raspberry Pi device
kill:
    @just _rpi --rpi-kill-app

# Starting application on Raspberry Pi device (first it will kill already running app) 
run:
    @just _rpi --rpi-run-app

# Copying application to Raspberry Pi device and then starting application
sync:
    @just _rpi --rpi-copy-code

# Live stream from Raspberry Pi device tmux session
tmux:
    @just _rpi --rpi-tmux
